backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
collections:
  - name: journal
    label: Journal
    folder: "site/journal"
    create: true
    fields:
      - label: "Title"
        name: "title"
media_folder: ""
media_library:
  name: "Photos"
